---
name: WWW-WebDevout-BrowserSupportInfo
version: 0.0102
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  access
  browser support API on L<http://webdevout.com>
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  Carp: 1.04
  LWP::UserAgent: 2.036
  URI: 1.35
  overload: 1.04
configure_requires:
  Module::Build: 0.34
provides:
  WWW::WebDevout::BrowserSupportInfo:
    file: lib/WWW/WebDevout/BrowserSupportInfo.pm
    version: 0.0102
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
