---
name: WWW-WebDevout-BrowserSupportInfo
version: 0.01
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: |-
  access
  browser support API on L<http://webdevout.com>
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  LWP::UserAgent: 2.036
  URI: 1.35
  overload: 1.04
build_requires:
  Test::More: 0
provides:
  WWW::WebDevout::BrowserSupportInfo:
    file: lib/WWW/WebDevout/BrowserSupportInfo.pm
    version: 0.01
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
